version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:580537134234:task-definition/etw:1"
        LoadBalancerInfo:
          ContainerName: "etw-stage"
          ContainerPort: 80